name: base
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.5.0
  - annotated-types=0.6.0
  - archspec=0.2.3
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - conda=25.1.1
  - conda-anaconda-telemetry=0.1.2
  - conda-anaconda-tos=0.1.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.1.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=43.0.3
  - distro=1.9.0
  - expat=2.6.4
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.11.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - menuinst=2.2.0
  - ncurses=6.4
  - nlohmann_json=3.11.2
  - openssl=3.0.15
  - packaging=24.2
  - pcre2=10.42
  - pip=25.0
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.9
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rich=13.9.4
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.8.0
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.67.1
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.5.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - attrs==25.3.0
      - bitsandbytes==0.45.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.4.1
      - deepspeed==0.16.4
      - dill==0.3.8
      - einops==0.8.1
      - filelock==3.16.1
      - fonttools==4.59.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - hjson==3.1.0
      - huggingface-hub==0.29.3
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.8.0.87
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - pandas==2.2.3
      - peft==0.15.0
      - pillow==11.0.0
      - propcache==0.3.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.3.0+git96316ce5
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - safetensors==0.5.3
      - six==1.17.0
      - sympy==1.13.3
      - tokenizers==0.21.1
      - torch==2.8.0.dev20250322+cu128
      - torchaudio==2.6.0.dev20250322+cu128
      - torchvision==0.22.0.dev20250322+cu128
      - transformers==4.50.0
      - tzdata==2025.1
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /home/jiaxuan/miniconda3
